### ISSUE TITLE
Bug in Phase Shift?

### ISSUE THREAD

**Issue by markeroon** [Tetrachrome/subpixel#20]
As an example
```
        x3 = np.arange(10*528*528*48).reshape(10, 528, 528, 48)
        X3 = tf.placeholder("float32", shape=(10, 528, 528, 48), name="X")# tf.Variable(x, name="X")
        Y3 = PS(X3, 3, color=True)
        y3 = sess.run(Y3, feed_dict={X3: x3})
```
this works fine when the second arg to PS is, say, 4, but it chokes when it's 3

```
  File "/home/user/Dev/subpixel/model.py", line 75, in build_model
    self.G = self.generator(self.inputs)
  File "/home/user/Dev/subpixel/model.py", line 191, in generator
    h2 = PS(h2, 3, color=True)
  File "/home/user/Dev/subpixel/subpixel.py", line 21, in PS
    Xc = tf.split(3, 3, X)
  File "/home/user/Dev/subpixel/subpixel.py", line 9, in _phase_shift
    X = tf.reshape(I, (bsize, a, b, r, r))
  File "/home/user/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2166, in reshape
    name=name)
  File "/home/user/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 748, in apply_op
    op_def=op_def)
  File "/home/user/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2405, in create_op
    set_shapes_for_outputs(ret)
  File "/home/user/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1790, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/home/user/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1696, in _ReshapeShape
    (num_elements, known_elements))
ValueError: input has 44605440 elements, which isn't divisible by 2509056

```

Any ideas?

**Comment by twinsyssy1018** [comment]
i also get similar error . i  think the PS function has bug ,mostly because the shape of output is not match with ground truth's. 
so i  only test the author's subpixel.py   like this ---
python subpixel.py

get error:

Tensor("Squeeze:0", shape=(), dtype=int32)
Traceback (most recent call last):
  File "subpixel.py", line 31, in <module>
    Y = PS(X, 2)
  File "subpixel.py", line 24, in PS
    X = _phase_shift(X, r)
  File "subpixel.py", line 10, in _phase_shift
    X = tf.reshape(I, (bsize, a, b, r, r))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 1092, in reshape
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 411, in apply_op
    as_ref=input_arg.is_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 566, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/constant_op.py", line 179, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/constant_op.py", line 162, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 332, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 272, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))

**Comment by IMG-PRCSNG** [comment]
Your input Image is of the shape `10 x 528 x 528 x 48` and you have mentioned that you are expecting a color image (of channels 3). Since each channel is done separately, the input to the phase_shift operator is evenly split into 3 parts along the last dimension and each part will be `10 x 528 x 528 x 16`dimension. But the last dimension must be **r**<sup>2</sup> since r is the factor by which each spatial dimension is upscaled. Thus it works only for `PS(X3, 4, color=True)` and will give you an output of `10 x 2112 x 2112 x 3`

If you want to upscale by a factor of 3, then the input must be `10 x 528 x 528 x 27` which will be passed as `10 x 528 x 528 x 9` for each of the three channel separately (and also notice 9 == 3<sup>2</sup> - for a scaling factor of 3) and you will get an output of `10 x 1584 x 1584 x 3`

In general if input is `bs x a x b x 3c` and if color is True, you can only use a factor of `r` such that `r == sqrt(c)` and you will get an output of `bs x ar x br x 3`. The operator is just a shuffling operator and the number of elements cannot change after the operation.

**Comment by BrianOn99** [comment]
@IMG-PRCSNG 
> But the last dimension must be r2 since r is the factor by which each spatial dimension is upscaled. 

Then there is a typo in README
```
In numpy, we can write this as

def PS(I, r):
  assert len(I.shape) == 3
  assert r>0
  r = int(r)
  O = np.zeros((I.shape[0]*r, I.shape[1]*r, I.shape[2]/(r*2)))
...
```

Should that be `O = np.zeros((I.shape[0]*r, I.shape[1]*r, I.shape[2]/(r**2)))`?

**Comment by IMG-PRCSNG** [comment]
@BrianOn99 Yes. It must be `r**2` as the total number of elements (N x H x W x C) in both the input and output must be same.
