### ISSUE TITLE
Tensorflow error on main.py

### ISSUE THREAD

**Issue by fraser-hemp** [Tetrachrome/subpixel#9]
Running OSX, I get this error on any python file I try to run
```
{'batch_size': 64,
 'beta1': 0.5,
 'checkpoint_dir': 'checkpoint',
 'dataset': 'celebA',
 'epoch': 25,
 'image_size': 128,
 'is_crop': True,
 'is_train': False,
 'learning_rate': 0.0002,
 'sample_dir': 'samples',
 'train_size': inf,
 'visualize': False}
Traceback (most recent call last):
  File "main.py", line 58, in <module>
    tf.app.run()
  File "/Library/Python/2.7/site-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "main.py", line 39, in main
    dataset_name=FLAGS.dataset, is_crop=FLAGS.is_crop, checkpoint_dir=FLAGS.checkpoint_dir)
  File "/Users/fraserhemp/Documents/subpixel/model.py", line 58, in __init__
    self.build_model()
  File "/Users/fraserhemp/Documents/subpixel/model.py", line 70, in build_model
    self.G = self.generator(self.inputs)
  File "/Users/fraserhemp/Documents/subpixel/model.py", line 155, in generator
    h2 = PS(h2, 4, color=True)
  File "/Users/fraserhemp/Documents/subpixel/subpixel.py", line 21, in PS
    X = tf.concat(3, [_phase_shift(x, r) for x in Xc])
  File "/Users/fraserhemp/Documents/subpixel/subpixel.py", line 9, in _phase_shift
    X = tf.reshape(I, (bsize, a, b, r, r))
  File "/Library/Python/2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 682, in reshape
    name=name)
  File "/Library/Python/2.7/site-packages/tensorflow/python/ops/op_def_library.py", line 411, in apply_op
    as_ref=input_arg.is_ref)
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/ops.py", line 529, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/Library/Python/2.7/site-packages/tensorflow/python/ops/constant_op.py", line 178, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/Library/Python/2.7/site-packages/tensorflow/python/ops/constant_op.py", line 161, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape))
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 319, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 259, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.
```

**Comment by EderSantana** [comment]
what is your tensorflow version??

**Comment by fraser-hemp** [comment]
0.7.1

**Comment by neerajBaji** [comment]
any solutions for this?

**Comment by EderSantana** [comment]
sorry, I tested only on Ubuntu with version 0.10 only. Did you try with a more recent version of TF? Try the docker version if problems persist.

Also, if somebody else fixes the problem for OSX, please let us know

**Comment by neerajBaji** [comment]
I used the latest tensorflow version 0.11 and I do not see this error.
Thanks.
